'use strict';

const $ = s => document.querySelector(s);
const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money = v => Number(v).toFixed(2).replace(/\.00$/, '');
const icons = {
  book:'<path d="M3 4c4-1 6 0 9 2 3-2 5-3 9-2v16c-4-1-6 0-9 2-3-2-5-3-9-2Z"/><path d="M12 6v16M6 9l3 1m-3 4 3 1m6-5 3-1m-3 6 3-1"/>',
  search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',
  heart:'<path d="M20.8 4.8a5.5 5.5 0 0 0-7.8 0L12 6l-1-1.2a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.4a5.5 5.5 0 0 0 0-7.8Z"/>',
  cart:'<path d="M2 3h3l3 13h11l3-9H6M9 20h.01M18 20h.01"/><circle cx="9" cy="20" r="1"/><circle cx="18" cy="20" r="1"/>',
  arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>', back:'<path d="m14 5-7 7 7 7"/>', down:'<path d="m7 10 5 5 5-5"/>',
  plus:'<path d="M12 5v14M5 12h14"/>', close:'<path d="m6 6 12 12M6 18 18 6"/>',
  location:'<path d="M19 10c0 6-7 11-7 11S5 16 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2.3"/>',
  leaf:'<path d="M20 3C7 1 2 10 6 16s16 3 14-13ZM4 21 16 9M9 16v-5m0 5h5"/>',
  scan:'<path d="M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5M6 12h12M8 7v3m4-3v3m4-3v3M8 15v2m4-2v2m4-2v2"/>',
  grid:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',
  home:'<path d="m3 10 9-7 9 7v11h-6v-7H9v7H3Z"/>',
  user:'<circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/>',
  camera:'<path d="M3 7h4l2-3h6l2 3h4v14H3Z"/><circle cx="12" cy="13" r="4"/>',
  chat:'<path d="M21 11a9 9 0 0 1-13 8l-5 2 1-6a9 9 0 1 1 17-4Z"/><path d="M8 11h8M8 7h5"/>',
  clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v6l4 2"/>',
  ticket:'<path d="M3 5h18v5a2 2 0 0 0 0 4v5H3v-5a2 2 0 0 0 0-4Z"/><path d="M15 5v3m0 3v2m0 3v3"/>',
  order:'<path d="M6 3h12v19l-3-2-3 2-3-2-3 2ZM9 7h6m-6 4h6m-6 4h3"/>',
  package:'<path d="m3 7 9-4 9 4-9 4Zm0 0v12l9 4 9-4V7M12 11v12M7 5l9 4v5"/>',
  edit:'<path d="m4 16-1 5 5-1L21 7l-6-4ZM13 5l6 6"/>',
  check:'<path d="m4 12 5 5L20 6"/>',
  star:'<path d="m12 2 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1Z"/>',
  wallet:'<path d="M3 6V3h15v4M3 6h18v15H3Zm12 5h6v6h-6Zm2 3h.1"/>',
  trash:'<path d="M3 6h18M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7m4-7v7"/>',
  shield:'<path d="M12 2 3 6v6c0 6 9 10 9 10s9-4 9-10V6Z"/><path d="m8 12 3 3 5-6"/>'
};
const icon = name => `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${icons[name] || icons.book}</svg>`;
const cats = ['全部','教材','教辅','文学','考研','其他'];
const colleges = ['全部学院','数学学院','计算机学院','外语学院','经管学院','文学院','草业学院','其他'];
const palettes = [
  ['#e7ebe0','#64795d','#f0ead5'],['#e9e6df','#dbc9a5','#5d553f'],['#e8edf0','#416b80','#e6ebdf'],
  ['#f0e6df','#b76647','#fff0d6'],['#e9e8ef','#756e8f','#f3eee3'],['#e8eadf','#c8cfaa','#3f5849'],
  ['#ece5dc','#6f6c54','#f5e4be'],['#e5eae9','#7c9b95','#f7f1d9']
];
const seeds = [
  [1,'高等数学（第七版）上册','高等数学','同济大学数学系','教材','数学学院',18,49.8,'九成新','少量铅笔笔记','陈同学','9787040396638','ADVANCED MATHEMATICS',0],
  [2,'人间草木','人间草木','汪曾祺','文学','文学院',16,39,'九成新','无划线 · 有书签','小满','9787530215634','A LITTLE OF EVERYTHING',1],
  [3,'Python 编程：从入门到实践','Python\n编程','埃里克·马瑟斯','教材','计算机学院',32,89,'八成新','含学习笔记','林同学','9787115428028','PYTHON CRASH COURSE',2],
  [4,'考研英语词汇红宝书','考研英语\n词汇','编写组','考研','外语学院',22,58,'九成新','词汇页干净','周同学','9787560448350','VOCABULARY NOTES',3],
  [5,'月亮与六便士','月亮与\n六便士','威廉·萨默塞特·毛姆','文学','文学院',12,35,'九成新','扉页有签名','阿禾','9787530216443','THE MOON AND SIXPENCE',4],
  [6,'新视野大学英语 · 读写教程 3','大学英语','郑树棠','教材','外语学院',19,49,'八成新','课堂笔记完整','许同学','9787513591904','NEW HORIZON ENGLISH',5],
  [7,'线性代数（第六版）','线性代数','同济大学数学系','教辅','数学学院',10,29,'九成新','无缺页','陆同学','9787040396614','LINEAR ALGEBRA',6],
  [8,'设计心理学','设计\n心理学','唐纳德·诺曼','其他','其他',25,59,'九成新','附原书腰','清和','9787508648333','THE DESIGN OF EVERYDAY THINGS',7],
  [9,'经济学原理 · 微观经济学','经济学\n原理','N. 格里高利·曼昆','教材','经管学院',28,69,'八成新','重点章节有标记','沈同学','9787301256886','PRINCIPLES OF ECONOMICS',1],
  [10,'数据结构（C 语言版）','数据结构','严蔚敏 / 吴伟民','教材','计算机学院',17,39,'九成新','附手写知识框架','叶同学','9787302147510','DATA STRUCTURES',0],
  [11,'植物学','植物学','陆时万','教材','草业学院',20,48,'八成新','插图清晰完整','安同学','9787040046854','BOTANY',5],
  [12,'考研数学复习全书','数学\n复习全书','李永乐','考研','数学学院',26,79,'全新','未使用','徐同学','9787560566900','MATHEMATICS REVIEW',2]
].map(([id,name,coverTitle,author,cat,college,price,origin,condition,note,seller,isbn,en,palette]) => ({id,name,coverTitle,author,cat,college,price,origin,condition,note,seller,isbn,en,palette,description:`${note}。书本保存完好，可以约在图书馆门口见面翻看。希望它能陪你走过下一个学期。`,place:'图书馆门口',created:100-id}));
const STORAGE = 'shiye-campus-v2';
const defaultState = () => ({profile:{name:'拾页同学',campus:'我的校园'},address:'图书馆门口',published:[],cart:[],favorites:[],history:[],orders:[],messages:{}});
let state = defaultState();
try {
  const saved = JSON.parse(localStorage.getItem(STORAGE));
  if(saved && typeof saved === 'object') {
    for(const k of ['published','cart','favorites','history','orders']) if(Array.isArray(saved[k])) state[k] = saved[k];
    if(saved.profile && typeof saved.profile.name==='string') state.profile = {...state.profile,...saved.profile};
    if(typeof saved.address==='string') state.address=saved.address;
    if(saved.messages && typeof saved.messages==='object' && !Array.isArray(saved.messages)) state.messages=saved.messages;
  }
} catch (_) {}
let route = '', selectedBook = 1, filter = {cat:'全部',college:'全部学院',query:'',sort:'recommended'}, collection = 'favorites';
let draft = {}, imageBusy = false, toastTimer, checkoutIds = null, dialogFocus = null;
const books = () => [...state.published,...seeds];
const bookById = id => books().find(b => b.id === Number(id));
const validCart = () => state.cart.filter(c => bookById(c.id) && c.qty>0);
const save = () => {
  try {localStorage.setItem(STORAGE, JSON.stringify(state));return true;}
  catch (_) {toast('浏览器储存空间不足，本次修改暂未保存。请移除较大的封面后重试。');return false;}
};
function toast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2700);}
function go(to){if(location.hash.slice(1)===to) render();else location.hash=to;}
function badge(){const n=validCart().reduce((s,c)=>s+c.qty,0);return n?`<span class="badge">${n}</span>`:'';}
function renderHeader(){
  const is = p => route === p ? 'active' : '';
  $('#header').innerHTML=`<a class="brand" href="#home" aria-label="拾页首页"><span class="brand-icon">${icon('book')}</span><span><strong>拾页</strong><small>PAGE AGAIN</small></span></a><nav class="desktop-nav" aria-label="桌面导航"><a class="${is('home')}" href="#home">发现好书</a><a class="${is('catalog')}" href="#catalog">分类书架</a><a class="${is('mine')}" href="#mine">我的拾页</a></nav><div class="header-end"><button class="campus-button" data-action="profile">${icon('location')}${esc(state.profile.campus)}${icon('down')}</button><a class="header-cart icon-button" href="#cart" aria-label="购物车">${icon('cart')}${badge()}</a><a class="btn" href="#publish">${icon('plus')}发布闲置</a><a class="avatar" href="#mine" aria-label="个人中心">${esc(state.profile.name.slice(0,1))}</a></div>`;
  $('#mobileNav').innerHTML=[['home','home','首页'],['catalog','grid','分类'],['publish','plus','发布'],['cart','cart','书袋'],['mine','user','我的']].map(([r,i,t])=>`<a href="#${r}" class="nav-item ${is(r)} ${r==='publish'?'publish':''}" ${route===r?'aria-current="page"':''}>${r==='publish'?`<span class="publish-icon">${icon(i)}</span>`:icon(i)}<span>${t}</span>${r==='cart'?badge():''}</a>`).join('');
}
function colorStyle(b){const p=palettes[b.palette%palettes.length]||palettes[0];return `--stage:${p[0]};--cover:${p[1]};--cover-ink:${p[2]}`;}
function cover(b){
  const photo = /^data:image\/(?:jpeg|png|webp);base64,/.test(b.image || '');
  return `<div class="book-cover ${photo?'has-photo':`theme-${b.id%4}`}" style="${colorStyle(b)}">${photo?`<img src="${esc(b.image)}" alt="${esc(b.name)}封面">`:`<span class="edition">PAGE AGAIN / BOOKS</span><b class="cover-title">${esc(b.coverTitle||b.name.slice(0,12)).replace(/\n/g,'<br>')}</b><span class="cover-en">${esc(b.en||'A NEW CHAPTER')}</span><span class="cover-decoration"></span><span class="cover-author">${esc(b.author||'校园书架')}</span>`}</div>`;
}
const mini = b => `<div class="mini-cover" style="${colorStyle(b)}">${cover(b)}</div>`;
const price = b => `<span class="price"><small>¥</small>${money(b.price)}<span class="old-price">¥${money(b.origin)}</span></span>`;
function cards(list){return list.length?list.map(b=>`<article class="book-card" data-book="${b.id}"><div class="cover-wrap"><button class="cover-button" data-action="detail" data-id="${b.id}" aria-label="查看${esc(b.name)}"><div class="book-stage" style="${colorStyle(b)}">${cover(b)}<span class="condition">${esc(b.condition)}</span></div></button><button class="heart-button ${state.favorites.includes(b.id)?'saved':''}" data-action="favorite" data-id="${b.id}" aria-label="${state.favorites.includes(b.id)?'取消收藏':'收藏'}${esc(b.name)}" aria-pressed="${state.favorites.includes(b.id)}">${icon('heart')}</button></div><div class="book-info"><div class="book-meta">${esc(b.cat)} / ${esc(b.college)}</div><button class="book-title" data-action="detail" data-id="${b.id}">${esc(b.name)}</button><div class="book-author">${esc(b.author||'校园同学')} · ${esc(b.note||b.condition)}</div><div class="price-row">${price(b)}<button class="add-cart" data-action="add" data-id="${b.id}" aria-label="加入书袋：${esc(b.name)}">${icon('plus')}</button></div><div class="seller-line"><span class="seller-dot">${esc(b.seller.slice(0,1))}</span>${esc(b.seller)}<span>校内面交</span></div></div></article>`).join(''):empty('没有找到这本书','换个关键词或分类，也许会有新的发现。','重置筛选','reset');}
function empty(title,text,label='去逛逛',action='home'){return `<div class="empty">${icon('book')}<h3>${title}</h3><p>${text}</p><button class="btn secondary" data-action="${action}">${label}${icon('arrow')}</button></div>`;}
function pageHead(title,sub='',back='home',extra=''){return `<div class="page-head"><a href="#${back}" class="icon-button" aria-label="返回">${icon('back')}</a><div><h1>${title}</h1>${sub?`<p>${sub}</p>`:''}</div>${extra?`<div class="head-end">${extra}</div>`:''}</div>`;}
const searchBox = () => `<label class="search">${icon('search')}<input id="searchInput" type="search" placeholder="搜索书名、作者或 ISBN" value="${esc(filter.query)}" aria-label="搜索书名、作者或 ISBN"><kbd>/</kbd></label>`;
function filters(){return `<div class="filter-row"><div class="chips" role="group" aria-label="图书分类">${cats.map(c=>`<button class="chip ${filter.cat===c?'active':''}" data-action="category" data-value="${c}" aria-pressed="${filter.cat===c}">${c}</button>`).join('')}</div><select id="sortSelect" class="sort-select" aria-label="图书排序">${[['recommended','综合推荐'],['price-low','价格从低到高'],['price-high','价格从高到低'],['newest','最新发布']].map(([v,t])=>`<option value="${v}" ${v===filter.sort?'selected':''}>${t}</option>`).join('')}</select></div>`;}
function filtered(){let list=books().filter(b=>(filter.cat==='全部'||b.cat===filter.cat)&&(route!=='catalog'||filter.college==='全部学院'||b.college===filter.college)&&[b.name,b.author,b.isbn].join(' ').toLowerCase().includes(filter.query.trim().toLowerCase()));if(filter.sort==='price-low')list.sort((a,b)=>a.price-b.price);if(filter.sort==='price-high')list.sort((a,b)=>b.price-a.price);if(filter.sort==='newest')list.sort((a,b)=>b.created-a.created);return list;}
function refreshResults(){const el=$('#bookGrid');if(el)el.innerHTML=cards(filtered());const count=$('#resultCount');if(count)count.textContent=`${filtered().length} 本好书，等待下一位读者`;}
function home(){return `<div class="topline"><p class="hello">你好，<b>${esc(state.profile.name)}</b>。今天也读几页吧。</p>${searchBox()}</div><section class="hero"><div class="hero-copy"><div class="eyebrow">CAMPUS BOOK EXCHANGE</div><h1>让好书，<br><em>再遇见。</em></h1><p>上一位同学的书，下一段故事的开始。<br>在校园里，把阅读的美好传下去。</p><a class="btn" href="#catalog">去淘一本好书${icon('arrow')}</a><span class="hero-note">${icon('leaf')}让阅读，循环生长</span></div><div class="hero-art" aria-hidden="true"><span class="art-star">✳</span><div class="art-sticker"><b>↻</b>好书再出发</div><div class="hero-book one"><small>READ · THINK · GROW</small><b>山野<br>有回声</b><small>每一页，都是新的开始</small></div><div class="hero-book two"><small>A LITTLE OF EVERYTHING</small><b>人间草木</b><small>汪曾祺 / 著</small></div><div class="hero-book three">THE NEXT CHAPTER · 拾页</div><div class="art-shelf"></div><span class="art-label">GOOD BOOKS NEVER GET OLD</span></div></section><div class="quick-links"><button class="quick-link" data-action="scan"><span class="quick-icon">${icon('scan')}</span><span><b>扫码估个价</b><small>扫一扫，旧书也有新价值</small></span>${icon('arrow')}</button><a class="quick-link" href="#catalog"><span class="quick-icon">${icon('grid')}</span><span><b>按学院找书</b><small>下一学期的书，提前备好</small></span>${icon('arrow')}</a><a class="quick-link" href="#publish"><span class="quick-icon">${icon('book')}</span><span><b>让闲置流转</b><small>把读完的故事，传给下一位</small></span>${icon('arrow')}</a></div><section id="shelf"><div class="section-heading"><div><div class="heading-inline"><h2>今日好书</h2><span class="eyebrow">THE CAMPUS EDIT</span></div><p id="resultCount">${filtered().length} 本好书，等待下一位读者</p></div></div>${filters()}<div class="book-grid" id="bookGrid">${cards(filtered())}</div></section><div class="bottom-note">读过的每一页，都不被浪费</div>`;}
function catalog(){return `${pageHead('分类书架','按兴趣发现，也按下一学期的课表寻找。')}<div class="catalog-banner">${icon('book')}<div><h2>你的课表，我们的书架。</h2><p>教材、教辅与课外好书，都在这里。</p></div></div><div class="catalog-tools">${searchBox()}<select class="select-input" id="collegeSelect" aria-label="选择学院">${colleges.map(c=>`<option ${c===filter.college?'selected':''}>${c}</option>`).join('')}</select></div>${filters()}<div class="book-grid" id="bookGrid">${cards(filtered())}</div>`;}
function detail(id){const b=bookById(id);if(!b)return empty('这本书暂时不在书架','可以再看看其他好书。');selectedBook=b.id;if(!state.history.includes(b.id)){state.history.unshift(b.id);state.history=state.history.slice(0,60);save();}return `${pageHead('好书详情','', 'catalog',`<button class="text-button" data-action="share">分享${icon('arrow')}</button>`)}<div class="detail-layout"><div class="detail-stage"><div class="book-stage" style="${colorStyle(b)}">${cover(b)}<span class="condition">${esc(b.condition)} · ${esc(b.note)}</span></div></div><div class="detail-copy"><span class="eyebrow">${esc(b.cat)} / ${esc(b.college)}</span><h1>${esc(b.name)}</h1><p class="muted tiny">${esc(b.author)} / 著</p><div class="price-row">${price(b)}<span class="pill">省下 ¥${money(Math.max(0,b.origin-b.price))}</span></div><div class="description">${esc(b.description)}</div><div class="detail-specs"><div><small>图书成色</small><b>${esc(b.condition)}</b></div><div><small>交易方式</small><b>校内面交</b></div><div><small>ISBN</small><b>${esc(b.isbn||'卖家未填写')}</b></div><div><small>约定地点</small><b>${esc(b.place)}</b></div></div><div class="seller-card"><span class="avatar">${esc(b.seller.slice(0,1))}</span><div><b>${esc(b.seller)}</b><p>${esc(b.own?'我的发布':'书架演示卖家')} · ${esc(b.college)}</p></div><span class="pill">${icon('leaf')} 以书会友</span></div><div class="detail-actions"><button class="icon-button ${state.favorites.includes(b.id)?'saved':''}" data-action="favorite" data-id="${b.id}" aria-label="收藏图书" aria-pressed="${state.favorites.includes(b.id)}">${icon('heart')}</button><a class="icon-button" href="#chat/${b.id}" aria-label="咨询图书">${icon('chat')}</a><button class="btn secondary" data-action="add" data-id="${b.id}">加入书袋</button><button class="btn" data-action="buy" data-id="${b.id}">预约这本书</button></div><p class="detail-fine">体验版：预约仅保存在当前浏览器，不会付款或通知真实卖家。</p></div></div>`;}
function cart(){const list=validCart();const total=list.reduce((s,c)=>s+Math.round(bookById(c.id).price*100)*c.qty,0)/100;return `${pageHead('我的书袋',`${list.reduce((s,c)=>s+c.qty,0)} 本书，等你带回去。`)}${!list.length?empty('书袋还空着','去找一本想读的书，把它放进来吧。'): `<div class="cart-layout"><div>${list.map(c=>{const b=bookById(c.id);return `<article class="cart-line">${mini(b)}<div class="cart-description"><a href="#detail/${b.id}"><h3>${esc(b.name)}</h3></a><p>${esc(b.condition)} · ${esc(b.seller)}</p>${price(b)}</div><div class="cart-controls"><button class="icon-button" data-action="remove" data-id="${b.id}" aria-label="移除${esc(b.name)}">${icon('trash')}</button><div class="stepper"><button data-action="qty" data-id="${b.id}" data-value="-1" aria-label="减少数量">−</button><span>${c.qty}</span><button data-action="qty" data-id="${b.id}" data-value="1" aria-label="增加数量">+</button></div></div></article>`;}).join('')}</div><aside class="panel summary"><h2>带走几页新故事</h2><div class="summary-row"><span>图书小计</span><b>¥${money(total)}</b></div><div class="summary-row"><span>校内面交</span><b>免运费</b></div><div class="summary-row total"><b>合计</b><span class="price">¥${money(total)}</span></div><button class="btn full" data-action="checkout">预约取书${icon('arrow')}</button><div class="notice-small">这是订单体验，不会扣款。你可以选择取书地点，生成预约后在「我的订单」查看。</div></aside></div>`}`;}
function field(name,label,type='text',value='',extra=''){return `<div class="field ${extra.includes('data-full')?'full':''}"><label for="${name}">${label}</label><input class="input" id="${name}" name="${name}" type="${type}" value="${esc(value)}" ${extra}></div>`;}
function selectField(name,label,options,value){return `<div class="field"><label for="${name}">${label}</label><select class="select-input" id="${name}" name="${name}">${options.map(o=>`<option ${o===value?'selected':''}>${o}</option>`).join('')}</select></div>`;}
function publish(){return `${pageHead('让好书，再出发','留下书的样子，也写下它的故事。','mine')}<form id="publishForm" class="form-layout"><div><button class="upload-cover" type="button" data-action="upload" id="coverPreview">${draft.image?`<img src="${esc(draft.image)}" alt="已选择的封面">`:`${icon('camera')}<b>拍一张书的照片</b><small>选择图片或拍照 · 最大 8 MB</small>`}</button><input class="hidden" type="file" id="coverInput" accept="image/jpeg,image/png,image/webp"><p class="form-note">封面会自动压缩。暂时没有照片，也可以使用拾页的文字书封。</p><button type="button" class="text-button" data-action="scan">${icon('scan')}用 ISBN 快速填写</button></div><div class="panel"><div id="formError" class="form-error" role="alert"></div><div class="form-grid">${field('name','书名 *','text',draft.name||'','required maxlength="70" data-full')}${field('author','作者','text',draft.author||'','maxlength="40"')}${field('isbn','ISBN','text',draft.isbn||'','maxlength="20" inputmode="numeric"')}${selectField('college','所属学院',colleges.slice(1),draft.college)}${selectField('cat','图书分类',cats.slice(1),draft.cat)}${field('origin','原价 / 元','number',draft.origin||'','min="0" max="9999" step="0.01"')}${field('price','出售价 / 元 *','number',draft.price||'','required min="0.01" max="9999" step="0.01"')}${selectField('condition','图书成色',['九成新','八成新','七成新','全新'],draft.condition)}${field('place','面交地点','text',draft.place||state.address,'maxlength="50"')}<div class="field full"><label for="description">描述一下这本书</label><textarea class="input" name="description" id="description" maxlength="600" placeholder="有没有笔记、折角？有什么想告诉下一位读者的？">${esc(draft.description||'')}</textarea></div></div><p class="form-note">体验版发布仅保存在此浏览器，其他设备暂时看不到。刷新后仍会保留。</p><button class="btn full" type="submit" id="publishSubmit">${icon('plus')}发布到我的书架</button></div></form>`;}
function mine(){const services=[['publish','book','我的发布'],['favorites','heart','我的收藏'],['history','clock','浏览记录'],['address','location','取书地点'],['coupons','ticket','我的书券'],['credit','star','我的足迹'],['wallet','wallet','钱包说明'],['help','chat','帮助中心']];return `<section class="profile-banner"><span class="avatar">${esc(state.profile.name.slice(0,1))}</span><div><h1>${esc(state.profile.name)}</h1><p>${esc(state.profile.campus)} · 以书会友，慢慢生长</p></div><button class="icon-button" data-action="profile" aria-label="编辑资料">${icon('edit')}</button></section><div class="profile-grid"><section class="panel"><div class="stats"><button class="stat" data-action="favorites"><b>${state.favorites.length}</b><small>收藏的好书</small></button><button class="stat" data-action="listings"><b>${state.published.length}</b><small>我发布的书</small></button><button class="stat" data-action="orders"><b>${state.orders.length}</b><small>预约记录</small></button></div><div class="panel-heading"><h2>我的书生活</h2><span class="eyebrow">MY LITTLE SHELF</span></div><div class="service-grid">${services.map(([a,i,t])=>`<button class="service" data-action="${a==='publish'?'listings':a}">${icon(i)}<span>${t}</span></button>`).join('')}</div></section><section class="panel"><div class="panel-heading"><h2>订单与消息</h2><a href="#orders" class="text-button">查看全部${icon('arrow')}</a></div><a class="list-row" href="#orders">${icon('package')}<span>待取书的预约<small>${state.orders.filter(o=>o.status==='pending').length} 笔预约等待面交</small></span>${icon('arrow')}</a><a class="list-row" href="#orders">${icon('check')}<span>读过的故事<small>${state.orders.filter(o=>o.status==='completed').length} 笔已完成记录</small></span>${icon('arrow')}</a><button class="list-row" data-action="conversations">${icon('chat')}<span>咨询记录<small>在这里找回保存的咨询</small></span>${icon('arrow')}</button><p class="form-note">你的资料和记录保存在当前设备。清除浏览器数据会一并清除。</p></section></div>`;}
function collectionPage(kind){const names={favorites:['我的收藏','那些让你想多读几页的好书。'],history:['浏览记录','找回刚才遇见的那一本。'],listings:['我的发布','给闲置的书，一个新去处。']};const [title,sub]=names[kind];let list=kind==='listings'?state.published:(kind==='history'?state.history:state.favorites).map(bookById).filter(Boolean);return `${pageHead(title,sub,'mine',kind==='listings'?'<a class="btn" href="#publish">发布新书</a>':'')}<div class="book-grid">${list.length?cards(list):empty('书架还是空的','把心动的书留下，让故事慢慢积累。',kind==='listings'?'去发布':'去逛逛',kind==='listings'?'publish':'home')}</div>${kind==='listings'&&list.length?`<div class="panel" style="margin-top:25px"><h3>管理我的书</h3>${list.map(b=>`<div class="list-row"><span>${esc(b.name)}</span><button class="text-button" style="margin-left:auto" data-action="unpublish" data-id="${b.id}">下架${icon('trash')}</button></div>`).join('')}</div>`:''}`;}
function orders(){return `${pageHead('我的订单','预约、取书，把故事接过来。','mine')}${!state.orders.length?empty('还没有预约记录','选一本喜欢的书，试试预约取书吧。'):state.orders.map(o=>`<article class="order-card"><div class="order-top"><span>${esc(o.date)} · ${esc(o.id)}</span><span class="pill">${({pending:'待取书 · 演示',completed:'已完成 · 演示',cancelled:'已取消',refunded:'售后已登记'})[o.status]}</span></div>${o.items.map(item=>`<div class="order-book">${mini(item.book)}<div><h3>${esc(item.book.name)}</h3><p>${esc(item.book.condition)} · ×${item.qty}</p><p>¥${money(item.book.price)}</p></div></div>`).join('')}<p class="form-note">取书地点：${esc(o.place)}${o.review?` · 我的评价：${esc(o.review)}`:''}</p><div class="order-bottom"><span class="tiny">预约合计 <b class="price">¥${money(o.total)}</b></span><div class="order-actions">${o.status==='pending'?`<button class="btn outline" data-action="cancel-order" data-id="${o.id}">取消预约</button><button class="btn" data-action="complete-order" data-id="${o.id}">模拟确认收书</button>`:''}${o.status==='completed'?`<button class="btn outline" data-action="refund-order" data-id="${o.id}">申请售后</button>${!o.review?`<button class="btn" data-action="review-order" data-id="${o.id}">写个评价</button>`:''}`:''}</div></div></article>`).join('')}`;}
function chat(id){const b=bookById(id);if(!b)return empty('书籍已下架','试试其他书吧。');selectedBook=b.id;const messages=state.messages[id]||[];return `<div class="chat-layout">${pageHead('与 '+esc(b.seller)+' 聊聊',esc(b.name),'detail/'+b.id)}<section class="panel"><p class="chat-hint">咨询演示：消息只保存在本机，下方回复由演示助手生成，不会发给卖家。</p><div class="chat-messages" id="chatMessages"><div class="message">你好，欢迎了解《${esc(b.name)}》。可以问问书况、价格和取书地点。</div>${messages.map(m=>`<div class="message ${m.me?'me':''}">${esc(m.text)}</div>`).join('')}</div><div class="quick-messages">${['书上有笔记吗？','可以在哪里面交？','还能便宜一点吗？'].map(t=>`<button data-action="quick-message" data-value="${t}">${t}</button>`).join('')}</div><form class="chat-input" id="chatForm"><input class="input" id="chatInput" aria-label="咨询消息" maxlength="500" placeholder="写下想问的问题…" required><button class="btn" type="submit">发送</button></form></section></div>`;}
function render(){
  const [r,id]=location.hash.slice(1).split('/');route=r||'home';if($('#dialog').open)$('#dialog').close();
  const views={home,catalog,cart,publish,mine,orders,favorites:()=>collectionPage('favorites'),history:()=>collectionPage('history'),listings:()=>collectionPage('listings'),detail:()=>detail(id),chat:()=>chat(id)};
  if(!views[route])route='home';renderHeader();$('#app').innerHTML=views[route]();document.title=route==='detail'&&bookById(id)?bookById(id).name+' · 拾页':'拾页 · 让好书，再遇见';window.scrollTo(0,0);
  if(route==='chat')$('#chatMessages').scrollTop=$('#chatMessages').scrollHeight;
}

// Actions and forms below keep user-created text escaped and state local to this browser.
function modal(title,body){dialogFocus=document.activeElement;const d=$('#dialog');d.innerHTML=`<div class="dialog-head"><h2 id="dialogTitle">${title}</h2><button class="icon-button" data-action="close" aria-label="关闭弹窗">${icon('close')}</button></div><div class="dialog-body">${body}</div>`;if(!d.open)d.showModal();}
function rerenderStay(){const y=scrollY;render();scrollTo(0,y);}
function add(id,quiet=false){const b=bookById(id);if(!b)return;const c=state.cart.find(x=>x.id===b.id);if(c){if(c.qty>=10){toast('单本图书最多加入 10 件');return;}c.qty++;}else state.cart.push({id:b.id,qty:1});save();renderHeader();if(!quiet)toast('已加入书袋，留给下一段阅读');}
function favorite(id){id=Number(id);state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[id,...state.favorites];save();if(route==='favorites')rerenderStay();else document.querySelectorAll(`[data-action="favorite"][data-id="${id}"]`).forEach(b=>{b.classList.toggle('saved',state.favorites.includes(id));b.setAttribute('aria-pressed',String(state.favorites.includes(id)));b.setAttribute('aria-label',state.favorites.includes(id)?'取消收藏图书':'收藏图书');});toast(state.favorites.includes(id)?'已收藏到我的书架':'已取消收藏');}
function checkout(id){checkoutIds=id?[{id:Number(id),qty:1}]:validCart().map(c=>({...c}));if(!checkoutIds.length)return;const total=checkoutIds.reduce((s,c)=>s+Math.round(bookById(c.id).price*100)*c.qty,0)/100;modal('预约取书',`<p>和下一本好书，约一个见面的地方。</p><div class="summary-row"><span>${checkoutIds.reduce((s,c)=>s+c.qty,0)} 本图书</span><strong>¥${money(total)}</strong></div><form id="checkoutForm">${field('meetPlace','取书地点 *','text',state.address,'required maxlength="60"')}<label class="tiny" style="display:flex;gap:8px;margin:16px 0"><input id="useCoupon" type="checkbox" ${total<30?'disabled':''}>使用体验书券：满 ¥30 减 ¥3</label><p class="terms">当前为本机订单演示。提交后不会扣款，也不会向真实卖家发送通知。</p><button class="btn full" type="submit">生成演示预约</button></form>`);}
function profile(){modal('我的校园名片',`<p>在书页之间，认识同样爱读书的你。</p><form id="profileForm">${field('nickname','昵称','text',state.profile.name,'required maxlength="16"')}${field('campus','学校或校区','text',state.profile.campus,'required maxlength="20"')}<p class="terms">资料仅保存在当前浏览器，不代表身份认证。</p><button class="btn full" type="submit">保存资料</button></form>`);}
function address(){modal('常用取书地点',`<p>选一个方便见面、能当面看书的校园公共场所。</p><form id="addressForm">${field('meetPlace','地点','text',state.address,'required maxlength="60"')}<button class="btn full" type="submit">保存地点</button></form>`);}
function scan(){
  if(route==='publish')captureDraft();
  modal('扫码估个价',`<p>拍摄书背面的 ISBN 条形码，或者直接输入 ISBN。</p><button class="scan-zone" style="width:100%" data-action="scan-photo">${icon('scan')}<span>拍摄 / 选择条形码照片</span></button><input class="hidden" type="file" id="barcodeInput" accept="image/*" capture="environment"><p id="scanHint" class="form-note">本机支持时直接识别；不支持时可手动输入。</p><form id="isbnForm">${field('isbnLookup','ISBN','text','','required maxlength="20" placeholder="例如 9787040396638" inputmode="numeric"')}<button class="btn full" type="submit">查书与参考估价</button></form><div id="isbnResult" aria-live="polite"></div>`);
}
function validISBN(s){if(/^\d{13}$/.test(s))return [...s].reduce((sum,v,i)=>sum+Number(v)*(i%2?3:1),0)%10===0;if(/^\d{9}[\dX]$/.test(s))return [...s].reduce((sum,v,i)=>sum+(10-i)*(v==='X'?10:Number(v)),0)%11===0;return false;}
function isbnLookup(){const isbn=$('#isbnLookup').value.replace(/[\s-]/g,'').toUpperCase();const el=$('#isbnResult');if(!validISBN(isbn)){el.innerHTML='<p class="form-error">ISBN 格式或校验位不正确，请检查书背面的 10 或 13 位号码。</p>';return;}const b=books().find(b=>b.isbn===isbn);if(b){el.innerHTML=`<div class="isbn-result"><h3>${esc(b.name)}</h3><p>${esc(b.author)} · ${esc(b.condition)}</p><p>书架参考价 <strong>¥${money(b.price)}</strong>（示例数据，非市场实时报价）</p><button class="btn full" data-action="prefill" data-id="${b.id}">带入发布表单</button></div>`;}else{draft.isbn=isbn;el.innerHTML='<div class="isbn-result"><p>ISBN 校验通过，当前书架没有收录这本书。你可以手动填写书名和售价。</p><button class="btn full" data-action="publish">继续发布</button></div>';}}
async function barcode(file){if(!file)return;const hint=$('#scanHint');if(!('BarcodeDetector' in window)){hint.textContent='当前浏览器不支持条码识别，请手动输入 ISBN。';return;}let bitmap;try{const formats=await BarcodeDetector.getSupportedFormats();if(!formats.includes('ean_13'))throw new Error('unsupported');bitmap=await createImageBitmap(file);const results=await new BarcodeDetector({formats:['ean_13']}).detect(bitmap);if(!results.length){hint.textContent='没有识别到 ISBN，请拍清晰的条形码或手动输入。';return;}$('#isbnLookup').value=results[0].rawValue;hint.textContent='已识别条码，请核对 ISBN。';isbnLookup();}catch(_){if(hint)hint.textContent='本次识别未成功，请手动输入 ISBN。';}finally{bitmap?.close();}}
function captureDraft(){const f=$('#publishForm');if(f)draft={...draft,...Object.fromEntries(new FormData(f))};}
async function upload(file){if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>8*1024*1024){toast('请选择不超过 8 MB 的 JPG、PNG 或 WebP 图片');return;}imageBusy=true;const submit=$('#publishSubmit');if(submit)submit.disabled=true;try{const bitmap=await createImageBitmap(file);const scale=Math.min(1,640/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();draft.image=canvas.toDataURL('image/jpeg',.78);if($('#coverPreview'))$('#coverPreview').innerHTML=`<img src="${draft.image}" alt="已选择的封面">`;toast('封面已准备好');}catch(_){toast('图片读取失败，请换一张照片');}finally{imageBusy=false;if(submit)submit.disabled=false;}}
function publishSubmit(form){if(imageBusy)return;captureDraft();const error=$('#formError');const name=draft.name.trim();const p=Number(draft.price),origin=Number(draft.origin)||0;const isbn=(draft.isbn||'').replace(/[\s-]/g,'').toUpperCase();if(!name||!Number.isFinite(p)||p<=0||p>9999||!Number.isFinite(origin)||origin<0||origin>9999){error.textContent='请填写书名和有效售价（¥0.01–9999）。';return;}if(isbn&&!validISBN(isbn)){error.textContent='ISBN 校验不通过；请修正或留空。';return;}const b={id:Date.now(),name,coverTitle:name.slice(0,10),author:draft.author.trim()||'作者未填写',cat:cats.includes(draft.cat)?draft.cat:'其他',college:colleges.includes(draft.college)?draft.college:'其他',price:Math.round(p*100)/100,origin:Math.round(Math.max(origin,p)*100)/100,condition:draft.condition||'九成新',note:'新发布',seller:state.profile.name,isbn,en:'A NEW CHAPTER',palette:state.published.length%palettes.length,description:draft.description.trim()||'这本书正在等待下一位读者。欢迎了解书况，约在校园见面。',place:draft.place.trim()||state.address,created:Date.now(),image:draft.image||'',own:true};state.published.unshift(b);if(!save()){state.published.shift();error.textContent='本机空间不足，发布未保存。请使用更小的封面。';return;}draft={};go('listings');toast('发布成功，已存入我的书架');}
function sendMessage(text){const b=bookById(selectedBook);text=(text||'').trim().slice(0,500);if(!b||!text)return;const key=String(b.id);const list=state.messages[key]||[];list.push({me:true,text});let answer;if(/笔记|成色|书况/.test(text))answer=`书架信息：${b.condition}，${b.note}。具体书况请在实际交易前当面确认。`;else if(/哪|地点|面交/.test(text))answer=`书架标注的面交地点是「${b.place}」。当前没有联系到卖家，正式交易前请另行确认时间。`;else if(/便宜|价格|多少钱/.test(text))answer=`当前标价 ¥${money(b.price)}。演示助手不能替卖家议价，你可以先收藏或生成演示预约。`;else answer='问题已保存在你的咨询记录中。这是本机演示，尚未发送给真实卖家。';list.push({me:false,text:answer});state.messages[key]=list.slice(-100);save();$('#app').innerHTML=chat(b.id);$('#chatMessages').scrollTop=$('#chatMessages').scrollHeight;$('#chatInput').focus();}
function orderAction(action,id){const o=state.orders.find(x=>x.id===id);if(!o)return;if(action==='review-order'){modal('写下这次相遇',`<form id="reviewForm" data-id="${esc(id)}"><div class="field"><label for="reviewText">我的阅读 / 取书感受</label><textarea id="reviewText" class="input" required maxlength="200" rows="4" placeholder="书况如何？期待怎样的阅读？"></textarea></div><p class="terms">评价仅保存在本机演示记录中。</p><button class="btn full" type="submit">保存评价</button></form>`);return;}const titles={'cancel-order':'取消这笔预约？','complete-order':'模拟确认收书？','refund-order':'登记售后申请？'};modal(titles[action],`<p>${action==='refund-order'?'体验版仅登记售后状态，不会执行真实退款。':'只会更新本机的演示订单记录，不涉及真实资金或消息发送。'}</p><button class="btn full" data-action="confirm-order" data-id="${esc(id)}" data-value="${action}">确认</button>`);}
function service(name){
  if(['home','catalog','publish','mine','orders','favorites','history','listings','cart'].includes(name)){go(name);return;}
  if(name==='profile')return profile();if(name==='address')return address();if(name==='scan')return scan();
  if(name==='coupons')modal('我的书券','<div class="coupon"><b>¥3</b><div><strong>新故事体验券</strong><p>满 ¥30 可用 · 仅演示订单使用</p></div></div><p>结算时勾选使用。书券不具备现金价值，体验版可重复体验。</p><button class="btn full" data-action="cart">去书袋看看</button>');
  if(name==='credit')modal('我的阅读足迹',`<p>阅读不必赶路，好书也值得再走一程。</p><div class="stats"><div class="stat"><b>${state.published.length}</b><small>本书重新出发</small></div><div class="stat"><b>${state.orders.filter(o=>o.status==='completed').length}</b><small>次完成的体验</small></div><div class="stat"><b>${state.favorites.length}</b><small>本心动好书</small></div></div><p class="terms">这些是本机使用记录，不是平台信用认证。</p>`);
  if(name==='wallet')modal('轻装阅读，不必充值',`<p>拾页当前不收款、不储存资金，也无需充值。演示预约的金额只用于展示订单流程。</p><div class="summary-row total"><span>真实扣款</span><b>¥0.00</b></div><button class="btn full" data-action="orders">查看预约记录</button>`);
  if(name==='help')modal('你好，这里是拾页',`<p><strong>怎样找书？</strong><br>搜索书名、作者、ISBN，或在分类书架选择学院和价格排序。</p><p><strong>发布和收藏会保存吗？</strong><br>会，记录留在当前浏览器。清除网站数据或更换设备后不会同步。</p><p><strong>能直接付款或联系卖家吗？</strong><br>当前是交互体验版。预约、咨询、售后均为本机演示，没有真实支付或消息发送。</p><p><strong>扫描条码不可用？</strong><br>部分微信浏览器不支持条码识别，可手动输入 ISBN 查找本地书架。</p><p><strong>交易前的小提醒</strong><br>真实面交时请核对版次、笔记和附件，在校园公共场所当面检查。</p>`);
  if(name==='conversations'){const ids=Object.keys(state.messages).filter(id=>state.messages[id].length&&bookById(id));modal('咨询记录',ids.length?ids.map(id=>`<a class="list-row" href="#chat/${id}">${icon('chat')}<span>${esc(bookById(id).name)}<small>${esc(state.messages[id].at(-1).text.slice(0,32))}</small></span>${icon('arrow')}</a>`).join(''):'<p>还没有咨询记录。先打开一本书，点击咨询图标试试。</p>');}
}
document.addEventListener('click',async event=>{
  const b=event.target.closest('[data-action]');if(!b)return;const {action,id,value}=b.dataset;
  if(action==='close'){$('#dialog').close();return;}
  if(action==='detail'){go('detail/'+id);return;}
  if(action==='favorite'){favorite(id);return;}
  if(action==='add'){if(bookById(id)?.own){toast('这是你发布的书，可在「我的发布」中管理');return;}add(id);return;}
  if(action==='buy'){if(bookById(id)?.own){go('listings');return;}checkout(id);return;}
  if(action==='checkout'){checkout();return;}
  if(action==='remove'){state.cart=state.cart.filter(c=>c.id!==Number(id));save();rerenderStay();return;}
  if(action==='qty'){const item=state.cart.find(c=>c.id===Number(id));if(item){item.qty=Math.min(10,item.qty+Number(value));state.cart=state.cart.filter(c=>c.qty>0);save();rerenderStay();}return;}
  if(action==='category'){filter.cat=value;document.querySelectorAll('[data-action="category"]').forEach(x=>{x.classList.toggle('active',x.dataset.value===value);x.setAttribute('aria-pressed',String(x.dataset.value===value));});refreshResults();return;}
  if(action==='reset'){filter={cat:'全部',college:'全部学院',query:'',sort:'recommended'};rerenderStay();return;}
  if(action==='upload'){$('#coverInput').click();return;}
  if(action==='scan-photo'){$('#barcodeInput').click();return;}
  if(action==='prefill'){const book=bookById(id);draft={...draft,name:book.name,author:book.author,isbn:book.isbn,price:book.price,origin:book.origin,college:book.college,cat:book.cat,condition:book.condition};$('#dialog').close();go('publish');return;}
  if(action==='quick-message'){sendMessage(value);return;}
  if(action==='unpublish'){modal('让这本书暂时休息？','<p>下架后会从书架和书袋中移除，已有订单仍保留。</p>'+`<button class="btn full" data-action="confirm-unpublish" data-id="${id}">确认下架</button>`);return;}
  if(action==='confirm-unpublish'){state.published=state.published.filter(b=>b.id!==Number(id));state.cart=state.cart.filter(c=>c.id!==Number(id));state.favorites=state.favorites.filter(x=>x!==Number(id));state.history=state.history.filter(x=>x!==Number(id));save();go('listings');toast('已下架');return;}
  if(['cancel-order','complete-order','refund-order','review-order'].includes(action)){orderAction(action,id);return;}
  if(action==='confirm-order'){const o=state.orders.find(o=>o.id===id);if(o){if(value==='cancel-order'&&o.status==='pending')o.status='cancelled';if(value==='complete-order'&&o.status==='pending')o.status='completed';if(value==='refund-order'&&o.status==='completed')o.status='refunded';save();go('orders');toast('演示订单状态已更新');}return;}
  if(action==='share'){if(bookById(selectedBook)?.own){modal('这本书在你的本机书架','<p>你发布的书仅保存在当前浏览器，还不能通过链接让其他设备看到。首页和示例图书可以直接分享。</p><a class="btn full" href="#home">返回首页</a>');return;}const url=new URL(location.href);url.hash='detail/'+selectedBook;try{await navigator.clipboard.writeText(url.href);toast('链接已复制，可以发给朋友');}catch(_){modal('分享这本书',`<p>复制下面的链接，发给想一起读书的人。</p><input class="input" readonly value="${esc(url.href)}" aria-label="分享链接">`);}return;}
  service(action);
});
document.addEventListener('input',e=>{if(e.target.id==='searchInput'){filter.query=e.target.value;refreshResults();}if(e.target.closest('#publishForm'))captureDraft();});
document.addEventListener('change',e=>{if(e.target.id==='sortSelect'){filter.sort=e.target.value;refreshResults();}if(e.target.id==='collegeSelect'){filter.college=e.target.value;refreshResults();}if(e.target.id==='coverInput')upload(e.target.files[0]);if(e.target.id==='barcodeInput')barcode(e.target.files[0]);if(e.target.closest('#publishForm'))captureDraft();});
document.addEventListener('submit',e=>{
  e.preventDefault();const f=e.target;
  if(f.id==='publishForm')return publishSubmit(f);
  if(f.id==='chatForm')return sendMessage($('#chatInput').value);
  if(f.id==='isbnForm')return isbnLookup();
  if(f.id==='profileForm'){const name=$('#nickname').value.trim(),campus=$('#campus').value.trim();if(!name||!campus)return toast('请填写昵称和校园');state.profile={name,campus};save();$('#dialog').close();render();toast('校园名片已保存');}
  if(f.id==='addressForm'){const p=$('#meetPlace').value.trim();if(!p)return toast('请填写取书地点');state.address=p;save();$('#dialog').close();toast('取书地点已保存');}
  if(f.id==='checkoutForm'){const place=$('#meetPlace').value.trim();if(!place||!checkoutIds?.length)return;const items=checkoutIds.map(c=>({book:bookById(c.id),qty:c.qty})).filter(c=>c.book);if(!items.length)return;const subtotal=items.reduce((s,c)=>s+Math.round(c.book.price*100)*c.qty,0)/100;const discount=$('#useCoupon').checked&&subtotal>=30?3:0;const o={id:'SY'+Date.now().toString().slice(-10),date:new Date().toLocaleDateString('zh-CN'),items,total:Math.round((subtotal-discount)*100)/100,discount,place,status:'pending'};const previousCart=state.cart;state.orders.unshift(o);state.cart=state.cart.filter(c=>!checkoutIds.some(x=>x.id===c.id));if(!save()){state.orders.shift();state.cart=previousCart;return;}checkoutIds=null;go('orders');toast('演示预约已生成，没有发生扣款');}
  if(f.id==='reviewForm'){const o=state.orders.find(o=>o.id===f.dataset.id);const text=$('#reviewText').value.trim();if(o&&text){o.review=text;save();go('orders');toast('评价已保存');}}
});
$('#dialog').addEventListener('click',e=>{if(e.target===$('#dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
$('#dialog').addEventListener('close',()=>{if(dialogFocus?.isConnected)dialogFocus.focus();});
document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)&&$('#searchInput')){e.preventDefault();$('#searchInput').focus();}});
window.addEventListener('hashchange',render);
render();
